### PR TITLE
Sharded corpus

### PR DESCRIPTION
**Pull request by piskvorky**
This PR makes the code work in Python 3 (pickle, xrange) too.

I also reformatted the docs to use imperative.

### CODE REVIEW

**Comment by piskvorky** [comment]
@hajicj : the package now loads in Python3, but tests still fail with exceptions like:

`ValueError: Attempting to load nonexistent shard no. 0.03`.

**Comment by piskvorky** [comment]
I think I fixed that one; still one error left:

`self.assertTrue(hasattr(dslice, 'next'))` inside `test_getitem_dense2gensim`.

What's that about?

**Comment by piskvorky** [comment]
I think I fixed that one too. Seems there are no more errors.

Honza, please review the changes and let's merge.

I'd like to get this functionality inside the new release of gensim, later this week. Cheers.

**Comment by hajicj** [comment]
Thanks!

The assertion is a check that the returned item is a generator (see methods _getitem_sparse2gensim() and _getitem_dense2gensim()). This is a relic of hopes to refactor slice/list-based retrieval so that it will be able to respond to larger-than-memory slice/list requests in gensim format, but it is currently useless -- for this to work, I'd have to rewrite the parts where the result is combined from multiple shards as a generator.

**Pull request merged**
